### ISSUE TITLE
Go To specific Page doesn't work with OSCWidgets

### ISSUE THREAD

**Issue by freekvdv** [benkuper/PowerPoint-OSC#1]
Hi,

Thanks for this tool.

I'm a novice in the OSC-world, so maybe I'm doing it all wrong, so sorry in advance. ;-)

I'm using OSCWidgets. 
"/next" & "/previous" is working fine, but "/page X" has no respons in Powerpoint.

Hope someone can help me out...

Powerpoint-version at the bottom.

![image](https://user-images.githubusercontent.com/48720708/54607808-938eec80-4a4f-11e9-878f-6ef4d55b8e8f.png)
![image](https://user-images.githubusercontent.com/48720708/54607951-ec5e8500-4a4f-11e9-87e7-b7fa1a448064.png)

**Comment by benkuper** [comment]
Hello,
I don't really know OSC Widgets (though it looks very interesting, I'll look into it)
I noticed that you are sending /**P**age instead of /**p**age : OSC is case-sensitive so you will need to send it with lowercase.
Also an OSC message has 2 differents parts :
- The address, which should **not** contain any spaces or special characters if not part of the OSC convention : http://opensoundcontrol.org/spec-1_0
- The arguments, that are a list of values (string, float, integer, color...) and are **independant** of the address. One common mistake for new users learning OSC is some OSC tools want to make OSC "user-friendly" by allowing them to mix the address and arguments on one line, whether it's with spaces or with "=", and that makes them not understand how OSC really works.
OSCWidgets seems to handle arguments, apparently with a weird syntax like /address=arg1,arg2,ar3
Just know that it it **NOT** how OSC works and sending this like that in any strict OSC software will not work, because you're just sending an OSC message with the address */address=arg1,arg2,arg3* and *no* arguments.
OSC Widgets apparently decided to parse this message itself to convert it to an OSCMessage /address with 3 arguments : arg1, arg2 and arg3.
In the case of PowerPointOSC, the message you want to send is /page (lowercase) with one integer argument being the number of the page.

Hope that helps !

**Comment by freekvdv** [comment]
Hi, thanks for your quick respons & extended explanation!
Makes a lot more sense now.

But, being no IT-er -& a lot of try and error- I can't figure out how to create the integer value in OSCWidgets.
If I fill in the Min or Max, I can create string or float arguments...

Sorry for being a noob...

PS: the /**P**age was part of the try & error. I tried a lot of /page before ;-);-);-)

**Comment by benkuper** [comment]
so apparently you could be able to do /page=1 
Otherwise, I initially made this module to be able to control it from Chataigne (http://benjamin.kuperberg.fr/chataigne) , can you try to create an OSC module (or a Powerpoint module directly) and control it from there ?

**Comment by freekvdv** [comment]
Thank you so much for your feedback!!!

/page=1 doesn't work unfortunately :-(

I downloaded Chatainge and yes! That worked!

So back to the drawboard for me now or still try to find out how I get integer arguments to work in OSCWidgets. Also on Github, so I'll post the question there...

Thank you again!

![image](https://user-images.githubusercontent.com/48720708/54644122-dd4ff500-4a98-11e9-885c-8258635ced12.png)

**Comment by benkuper** [comment]
Good to know :) Just so you know, there is a module "Software > Powerpoint" in Chataigne that already integrates the command, if you're interested :)
